version: '3.8'
services:
    app:
        platform: linux/amd64
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-app
        container_name: laravel-app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - .:/var/www
        ports:
            - "8000:8000"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
